## Numpy


In [18]:
# Installation Numpy
# Docs: https://numpy.org/doc/stable/user/index.html
# NDARRAY: https://numpy.org/doc/stable/reference/arrays.ndarray.html
# 
# pip install numpy
# ou
# python -m pip install numpy


import numpy as np

data = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ndarray
print(type(data))

print(data)

print(data.dtype)

<class 'numpy.ndarray'>
[1.  2.  3.  4.  5.  6.8 7.  8.  9. ]
float64


In [35]:
# array_1d = np.array([7, 2, 9, 10])

# print(array_1d)
# print(array_1d.ndim)
# print(array_1d.shape)


# array_2d = np.array([[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]])

# print(array_2d)
# print(array_2d.ndim)
# print(array_2d.shape)


array_3d = np.array([ [ [1, 2], [3, 4] ], [ [ 5, 6 ], [7, 8] ] ])

print(array_3d)
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
64


#### Filter data with `numpy`

In [38]:
data = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])

even_numbers = data[ data % 2 == 0 ]
odd_numbers = data[ data % 2 != 0]

print(even_numbers, odd_numbers)

[2 4 6 8] [1 3 5 7 9]


#### Order data with `numpy`

In [42]:
data = np.array([ 12, 3, 8, 6,22, 43, 2, 34, 26, 15 ])

asc = np.sort(data)

print(asc)

[ 2  3  6  8 12 15 22 26 34 43]


In [45]:
fruits = np.array(['orange', 'pomme', 'ananas', 'banane'])

sorted_fruits = np.sort(fruits)

print(sorted_fruits)

['ananas' 'banane' 'orange' 'pomme']
